import { describe, expect, test } from "bun:test";
import { formatHtml } from "../../src/formatters/html.js";
import type { Finding, ScanResult } from "../../src/types.js";

function makeFinding(overrides: Partial<Finding> = {}): Finding {
  return {
    detectorId: "test-detector",
    message: "Test issue found",
    severity: "warning",
    file: "src/utils.ts",
    line: 3,
    column: 5,
    ...overrides,
  };
}

function makeResult(overrides: Partial<ScanResult> = {}): ScanResult {
  return {
    findings: [],
    filesScanned: 1,
    errors: [],
    ...overrides,
  };
}

describe("formatHtml", () => {
  test("outputs valid HTML structure", () => {
    const result = makeResult({
      findings: [makeFinding()],
      filesScanned: 5,
    });

    const output = formatHtml(result);

    expect(output).toContain("<!DOCTYPE html>");
    expect(output).toContain("<html");
    expect(output).toContain("</html>");
    expect(output).toContain("<head>");
    expect(output).toContain("</head>");
    expect(output).toContain("<body>");
    expect(output).toContain("</body>");
  });

  test("contains summary counts", () => {
    const result = makeResult({
      findings: [
        makeFinding({ severity: "error" }),
        makeFinding({ severity: "error" }),
        makeFinding({ severity: "warning" }),
        makeFinding({ severity: "info" }),
      ],
      filesScanned: 10,
    });

    const output = formatHtml(result);

    // Total findings
    expect(output).toContain(">4</div>");
    // Error count
    expect(output).toContain('"count count-error">2</div>');
    // Warning count
    expect(output).toContain('"count count-warning">1</div>');
    // Info count
    expect(output).toContain('"count count-info">1</div>');
    // Files scanned
    expect(output).toContain('"count count-files">10</div>');
  });

  test("contains finding details", () => {
    const result = makeResult({
      findings: [
        makeFinding({
          file: "src/app.ts",
          line: 42,
          column: 7,
          severity: "error",
          message: "Something is wrong",
          detectorId: "my-rule",
        }),
      ],
    });

    const output = formatHtml(result);

    expect(output).toContain("src/app.ts");
    expect(output).toContain("42:7");
    expect(output).toContain("error");
    expect(output).toContain("my-rule");
    expect(output).toContain("Something is wrong");
  });

  test("groups findings by file", () => {
    const result = makeResult({
      findings: [
        makeFinding({ file: "src/a.ts", line: 1 }),
        makeFinding({ file: "src/a.ts", line: 5 }),
        makeFinding({ file: "src/b.ts", line: 3 }),
      ],
    });

    const output = formatHtml(result);

    // Both file names appear as headings
    expect(output).toContain("src/a.ts");
    expect(output).toContain("src/b.ts");

    // File a has 2 findings
    expect(output).toContain("src/a.ts</code> <span");
    expect(output).toContain("(2)");
    // File b has 1 finding
    expect(output).toContain("src/b.ts</code> <span");
    expect(output).toContain("(1)");
  });

  test("handles empty results", () => {
    const result = makeResult({
      findings: [],
      errors: [],
      filesScanned: 0,
    });

    const output = formatHtml(result);

    expect(output).toContain("<!DOCTYPE html>");
    expect(output).toContain("</html>");
    expect(output).toContain("No problems found.");
    expect(output).toContain('"count count-total">0</div>');
    expect(output).toContain('"count count-error">0</div>');
    expect(output).toContain('"count count-files">0</div>');
  });

  test("includes inline CSS", () => {
    const result = makeResult({ findings: [] });

    const output = formatHtml(result);

    expect(output).toContain("<style>");
    expect(output).toContain("</style>");
    // Check some key CSS rules exist
    expect(output).toContain(".severity-error");
    expect(output).toContain(".severity-warning");
    expect(output).toContain(".severity-info");
    expect(output).toContain(".badge");
  });

  test("includes footer with version", () => {
    const result = makeResult({ findings: [] });

    const output = formatHtml(result);

    expect(output).toContain("Generated by vibecop v0.1.0");
    expect(output).toContain("<footer>");
  });

  test("escapes HTML special characters in messages", () => {
    const result = makeResult({
      findings: [
        makeFinding({
          message: 'Found <script>alert("xss")</script> in code',
          file: "src/test&file.ts",
        }),
      ],
    });

    const output = formatHtml(result);

    // Should not contain raw angle brackets from the finding
    expect(output).toContain("&lt;script&gt;");
    expect(output).toContain("&amp;file.ts");
    expect(output).not.toContain('<script>alert("xss")</script>');
  });

  test("renders severity badges with correct classes", () => {
    const result = makeResult({
      findings: [
        makeFinding({ severity: "error", detectorId: "rule-1" }),
        makeFinding({ severity: "warning", detectorId: "rule-2" }),
        makeFinding({ severity: "info", detectorId: "rule-3" }),
      ],
    });

    const output = formatHtml(result);

    expect(output).toContain('class="badge severity-error"');
    expect(output).toContain('class="badge severity-warning"');
    expect(output).toContain('class="badge severity-info"');
  });
});
